[package]
name = "wik-dps-tp01"
version = "0.1.0"
edition = "2021"

# Dépendances minimales
[dependencies]
# Pour la gestion des variables d'environnement
dotenv = "0.15.0"
# Pour la sérialisation/désérialisation JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
